### ISSUE TITLE
v1 Roadmap

### ISSUE THREAD

**Issue by asg017** [asg017/observable-prerender#2]
- [ ] Set up automated testing for this repo. Getting puppeteer to work on Github Actions is pretty painful, so I just resorted to local tests. PRs welcome!
- [ ] Move puppeteer to a npm peerDepedency, so greatly reduce this package's size.
- [ ] There might be some bugs/unexpected behavior when loading an entire notebook (as opposed to just a portion).
- [ ] Support `define` functions in `load`. That way, people could load local notebooks instead of relying on observablehq.com
